### ISSUE TITLE
Error when querying with Mcollective

### ISSUE THREAD

**Issue by SOLDIERz** [cernops/mcollective-foreman#5]
mco rpc rpcutil ping --dm=foreman --do='name=node.example.com' -v
Discovering hosts using the foreman method .... Username:
*******
Password:
*******

The rpc application failed to run: uninitialized constant Errno::EHOST

uninitialized constant Errno::EHOST (NameError)
        from /usr/libexec/mcollective/mcollective/discovery/foreman.rb:55:in `rescue in get_ssl'  <----
        from /usr/libexec/mcollective/mcollective/discovery/foreman.rb:50:in `get_ssl'
        from /usr/libexec/mcollective/mcollective/discovery/foreman.rb:38:in `get'
        from /usr/libexec/mcollective/mcollective/discovery/foreman.rb:29:in `discover'
        from /usr/share/ruby/vendor_ruby/mcollective/discovery.rb:134:in `discover'
        from /usr/share/ruby/vendor_ruby/mcollective/client.rb:151:in `discover'
        from /usr/share/ruby/vendor_ruby/mcollective/rpc/client.rb:548:in `discover'
        from /usr/libexec/mcollective/mcollective/application/rpc.rb:112:in `main'
        from /usr/share/ruby/vendor_ruby/mcollective/application.rb:291:in `run'
        from /usr/share/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
        from /usr/bin/mco:24:in `<main>'

client.cfg:

plugin.foreman.url = https://foreman.example.com
plugin.foreman.ssl_cert = /var/lib/puppet/ssl/certs/node.example.com.pem
plugin.foreman.ssl_key  = /var/lib/puppet/ssl/private_keys/node.example.com.pem
plugin.foreman.use_krb  = 0
direct_addressing = 1

Any help here? Also don't understand why I need to enter Username and Password here...

**Comment by traylenator** [comment]
I am guessing you don't have a host foreman.example.com ? You need to change the url
to point to your foreman host. 
The username and password are the basic auth passwords to foreman.

**Comment by SOLDIERz** [comment]
That's right. I just replaced it with some example. So any help?

**Comment by AlbertoPeon** [comment]
My guess will be that the plugin is complaining because can't read the SSL certificate.

Do you have the SSL cert and key in "/var/lib/puppet/ssl/certs/node.example.com.pem" and  "/var/lib/puppet/ssl/private_keys/node.example.com.pem" ?

**Comment by SOLDIERz** [comment]
Nope. In the current setup I don't use any SSL-Encryption for mcollective

**Comment by AlbertoPeon** [comment]
The plugin will assume that you are using SSL if the value of "plugin.foreman.url" starts with "https"

**Comment by traylenator** [comment]
The s in the https part of the pluginf foreman url refers to your foreman service. This URL is the URL you use in your webbrowser to viist your foreman web page.

The encyption status of mcollective middleware itself is irrelevant to this plugin.foreman.url.

How do you normally login into your foreman web page? With password?

**Comment by traylenator** [comment]
Closing due to lack of activity.

**Comment by rashkinadze** [comment]
I have the same issue.  I log into foreman with a username and password.  I have added the following to my ~/.mcollective -

plugin.foreman.url = https://XXX.com:443
plugin.foreman.ssl_cert = /Users/xxx/.puppet/ssl/certs/xxx-15-macbook-pro.local.pem
plugin.foreman.ssl_key  = /Users/xxx/.puppet/ssl/private_keys/xxx-15-macbook-pro.local.pem
plugin.foreman.use_krb  = 0
